server:
  port: 8202
spring:
  application:
    name: service-cmn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.135.140:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.135.140
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

