server:
  port: 8201
spring:
  application:
    name: service-hosp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.135.140:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://192.168.135.140:27017/test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.135.140
    password: guest
    port: 5672
    username: guest



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl